language: python

os: linux

dist: bionic

git:
  depth: 1
  
python:
  # bionic LTS versions
  - 3.6.10 
  - 3.7.6
  - 3.8.2
  
install:
  - pip install -r requirements.txt

script:
  - python run.py > run-output.txt

cache: 
  pip: true
